### ISSUE TITLE
After deployment site is not working

### ISSUE THREAD

**Issue by lokesh932338** [lokesh932338/news-website#1]

**Comment by SAGARSINGH-1** [comment]
The problem is that when the data is not delivered from the API call and you are using it already.

**Comment by SAGARSINGH-1** [comment]
Make these changes on line number 17 and 18

<img width="279" alt="image" src="https://github.com/lokesh932338/news-website/assets/81561733/2fe5d31c-bc6c-4dae-a485-e706513526e7">

 **like this**

**Comment by SAGARSINGH-1** [comment]
Bro your API is giving ERROR; you can't use it. It states that requests from the browser are not allowed on the Developer plan of the News API, except when the request is coming from localhost.

![image](https://github.com/lokesh932338/news-website/assets/81561733/ccea4a91-4cdc-478c-9dba-50104e517473)


**In other words, the News API you are using has CORS restrictions, and it only allows requests from localhost**

**Comment by lokesh932338** [comment]
> Bro your API is giving ERROR; you can't use it. It states that requests from the browser are not allowed on the Developer plan of the News API, except when the request is coming from localhost.
> 
> ![image](https://user-images.githubusercontent.com/81561733/269376334-ccea4a91-4cdc-478c-9dba-50104e517473.png)
> 
> **In other words, the News API you are using has CORS restrictions, and it only allows requests from localhost**

OK
